name: projek_flutter_akhir
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
